dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: esm/esm_mutation_dataset/FluorescenceDataset
  dataloader_kwargs: # deprecated, initalized through training args
    batch_size: 8
    num_workers: 8

  train_lmdb: /cto_labs/AIDD/DATA/SaProt/fluorescence/fluorescence_train.lmdb
  valid_lmdb: /cto_labs/AIDD/DATA/SaProt/fluorescence/fluorescence_valid.lmdb
  test_lmdb: /cto_labs/AIDD/DATA/SaProt/fluorescence/fluorescence_test.lmdb
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: /cto_labs/AIDD/WEIGHTS/Protein/esm2_t6_8M_UR50D
    max_length: 1024